#pragma once

#include "Network/PacketData/PacketDataServer/PacketDataJoinQuery.hpp"
#include "Network/PacketData/PacketDataServer/PacketDataJoinReply.hpp"
#include "Network/PacketData/PacketDataServer/PacketDataJoinInfo.hpp"
#include "Network/PacketData/PacketDataServer/PacketDataPlayerJoined.hpp"
#include "Network/PacketData/PacketDataServer/PacketDataServerInfo.hpp"
#include "Network/PacketData/PacketDataServer/PacketDataChatMessage.hpp"

#include "Network/PacketData/PacketDataPlayer/PacketDataPlayerData.hpp"
#include "Network/PacketData/PacketDataPlayer/PacketDataPlayerCharacterInfo.hpp"
#include "Network/PacketData/PacketDataPlayer/PacketDataInventoryAddItem.hpp"

#include "Network/PacketData/PacketDataWorld/PacketDataObjectHit.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataObjectBuilt.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataObjectDestroyed.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataMeleeRequest.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataLandPlaced.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataItemPickupsCreated.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataItemPickupCollected.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataItemPickupsCreateRequest.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataChestOpened.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataChestClosed.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataChestDataModified.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataChunkDatas.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataChunkRequests.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataChunkModifiedAlerts.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataEntities.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataProjectiles.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataProjectileCreateRequest.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataBosses.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataBossSpawnCheck.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataBossSpawnCheckReply.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataBossSpawnRequest.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataMapChunkDiscovered.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataLandmarks.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataLandmarkModified.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataRocketEnterRequest.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataRocketEnterReply.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataRocketInteraction.hpp"
#include "Network/PacketData/PacketDataWorld/PacketDataParticle.hpp"

#include "Network/PacketData/PacketDataTravel/PacketDataPlanetTravelRequest.hpp"
#include "Network/PacketData/PacketDataTravel/PacketDataPlanetTravelReply.hpp"
#include "Network/PacketData/PacketDataTravel/PacketDataRoomTravelRequest.hpp"
#include "Network/PacketData/PacketDataTravel/PacketDataRoomTravelReply.hpp"
#include "Network/PacketData/PacketDataTravel/PacketDataStructureEnterRequest.hpp"
#include "Network/PacketData/PacketDataTravel/PacketDataStructureEnterReply.hpp"